### PR TITLE
Add pyi for TypeHint

### PR DESCRIPTION
**Pull request by nrtkbb**
In this pull request, I've added .pyi files for the existing Python modules.
This enhancement allows for improved code completion in IDEs that utilize TypeHints and enables static code analysis.

### CODE REVIEW

**Comment by sol-ansano-kim** [comment]
Hi, thank you for contributing.

Would you mind adding your author info into the pyi file?

Also just a heads up, it might not install pyi when you build it as is. if want to it to be installed, need to add it to Scons build script. ( SConstruct line 153 )

**Comment by nrtkbb** [comment]
Thank you very much for publishing this wonderful tool here. 

I added the author name to the pyi file, is this correct?

I installed Scons on macOS and gave with-maya=2024 to build and confirmed.
I was able to confirm that by modifying SConstruct line 153 as you suggested, medic.pyi is also copied to release/py/2024.

**Comment by sol-ansano-kim** [comment]
I apologize for my lack of clarity earlier. I'd appreciate it if you could leave the initial comment as it is. (I should have provided guidelines for contributions.)

**Comment by sol-ansano-kim** [comment]
Something like this is enough
```
"""file name : medic.pyi
author : your name <your email > (Unless you hate writing email adress)
"""
```

**Comment by nrtkbb** [comment]
Thank you for sharing how to write auther.
I have modified it, is it correct?

**Comment by sol-ansano-kim** [comment]
It looks good to me. Thank you for PR

**Pull request merged**
